name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request: 
    branches: ["main"]

jobs:

  build:

    runs-on: self-hosted

    env:
      REPO_NAME: ${{ github.event.repository.name }}
      GIT_URL: ${{ github.server_url }}/${{ github.repository }}.git
      TAG: ${{ github.sha }}

    steps:

      - uses: actions/checkout@v4

      - name: Build image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --load \
            -t ${{ vars.REGISTRY_URL }}/${REPO_NAME}:${TAG} \
            .

      - name: Push image
        run: |
          docker push ${{ vars.REGISTRY_URL }}/${REPO_NAME}:${TAG}

#      - name: Trigger Jenkins CD
#        run: |
#          curl -X POST \
#            "${{ vars.JENKINS_URL }}/job/${{ vars.JENKINS_JOB }}/buildWithParameters" \
#            --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" \
#            --data-urlencode "api_name=${REPO_NAME}" \
#            --data-urlencode "GIT_URL=${GIT_URL}" \
#            --data-urlencode "branch=main" \
#            --data-urlencode "TAG=${TAG}"
      - name: CD
        run: |
          bash deploy_helm.sh ./cd ${REPO_NAME}.ydphoto.com ${REPO_NAME} ${TAG} dev
