name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build image
      run: |
        docker build \
          -t 192.168.50.18:5000/myapp:${{ github.sha }} \
          .
    - name: Push image
      run: |
        docker push 192.168.50.18:5000/myapp:${{ github.sha }}
